### ISSUE TITLE
interceptor "STATUS_STACK_BUFFER_OVERRUN"

### ISSUE THREAD

**Issue by nblog** [frida/frida-gum#655]
chrome version: **90.0.4430.93**  or  **last version**

**inject code:**
```
/* chrome ver: 90.0.4430.93 */

function chromium_symbol(chromium_core) {

    let base = new NativePointer(chromium_core.base);

    return {

        "net::URLRequestContext": {
            "URLRequestContext::CreateRequest": base.add(0x1AE600),
        }

    }

}

var symbol = chromium_symbol( Process.getModuleByName("chrome.dll") );


function trace_chromium_URLRequest() {

    Interceptor.attach( symbol["net::URLRequestContext"]["URLRequestContext::CreateRequest"] , {
        onEnter(args) {

        },
        onLeave(retval) {

        }
    });

}


trace_chromium_URLRequest();
```

![image](https://user-images.githubusercontent.com/10218627/168023795-a6ba7093-928f-427c-a6bd-e3521d183626.png)
```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: C0000409 (STATUS_STACK_BUFFER_OVERRUN)
          ExceptionFlags: 00000001
        ExceptionAddress: 00007FFAE478E666 chrome.00007FFAE478E666
        NumberParameters: 1
ExceptionInformation[00]: 0000000000000039
```

i have also tried to use "frida-gum" library, which will cause the same problem.
